#include "VRTLog.h"

DEFINE_LOG_CATEGORY(LogVRT);
DEFINE_LOG_CATEGORY(LogVRTInput);
DEFINE_LOG_CATEGORY(LogVRTPawn);
DEFINE_LOG_CATEGORY(LogVRTHand);
DEFINE_LOG_CATEGORY(LogVRTHolster);
DEFINE_LOG_CATEGORY(LogVRTWeapon);
DEFINE_LOG_CATEGORY(LogVRTTwoHand);
DEFINE_LOG_CATEGORY(LogVRTProjectile);
DEFINE_LOG_CATEGORY(LogVRTGameFlow);
DEFINE_LOG_CATEGORY(LogVRTMaze);
DEFINE_LOG_CATEGORY(LogVRTNav);
DEFINE_LOG_CATEGORY(LogVRTAI);
DEFINE_LOG_CATEGORY(LogVRTDirector);
DEFINE_LOG_CATEGORY(LogVRTCombat);
DEFINE_LOG_CATEGORY(LogVRTFlat);
